### ISSUE TITLE
Cannot find module '/node_modules/gatsby-cli/lib/index.js'

### ISSUE THREAD

**Issue by marcpicaud** [nrwl/gatsby#19]
Hi,

On a fresh install, an error is thrown when trying to serve a gatsby app, please see below.

## Steps to reproduce :
`npx create-nx-workspace gatsby` (empty)
`npm install @nrwl/gatsby --save-dev`
`nx generate @nrwl/gatsby:app myblog` (scss)
`nx serve myblog`

> nx run myblog:serve
> internal/modules/cjs/loader.js:638
>    throw err;
>    ^
>
> Error: Cannot find module '/path/to/my/nx-workspace/node_modules/gatsby-cli/lib/index.js'
>    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
>    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
>  at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
>   at startup (internal/bootstrap/node.js:283:19)
>    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
> Error during serve 

## package.json

```
{
  "name": "gatsby",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "nx": "nx",
    "start": "nx serve",
    "build": "nx build",
    "test": "nx test",
    "lint": "nx workspace-lint && nx lint",
    "e2e": "nx e2e",
    "affected:apps": "nx affected:apps",
    "affected:libs": "nx affected:libs",
    "affected:build": "nx affected:build",
    "affected:e2e": "nx affected:e2e",
    "affected:test": "nx affected:test",
    "affected:lint": "nx affected:lint",
    "affected:dep-graph": "nx affected:dep-graph",
    "affected": "nx affected",
    "format": "nx format:write",
    "format:write": "nx format:write",
    "format:check": "nx format:check",
    "update": "nx migrate latest",
    "workspace-schematic": "nx workspace-schematic",
    "dep-graph": "nx dep-graph",
    "help": "nx help"
  },
  "private": true,
  "dependencies": {
    "gatsby": "2.20.24",
    "gatsby-image": "2.2.39",
    "gatsby-plugin-svgr": "2.0.2",
    "gatsby-plugin-manifest": "2.2.39",
    "gatsby-plugin-offline": "3.0.32",
    "gatsby-plugin-react-helmet": "3.1.21",
    "gatsby-plugin-sharp": "2.4.3",
    "gatsby-source-filesystem": "2.1.46",
    "gatsby-transformer-sharp": "2.3.13",
    "prop-types": "15.7.2",
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "react-helmet": "5.2.1",
    "gatsby-plugin-typescript": "2.4.0"
  },
  "devDependencies": {
    "@nrwl/gatsby": "^0.940.0-beta.0",
    "@nrwl/workspace": "9.4.5",
    "@types/node": "~8.9.4",
    "dotenv": "6.2.0",
    "eslint": "6.8.0",
    "prettier": "2.0.4",
    "ts-node": "~7.0.0",
    "tslint": "~6.0.0",
    "typescript": "~3.8.3",
    "@nrwl/jest": "9.4.5",
    "jest": "25.2.3",
    "@types/jest": "25.1.4",
    "ts-jest": "25.2.1",
    "cypress": "^4.1.0",
    "@nrwl/cypress": "9.4.5",
    "@angular-devkit/schematics": "9.1.7",
    "@nrwl/react": "9.4.0-rc.6",
    "@testing-library/react": "10.2.1",
    "babel-plugin-module-resolver": "4.0.0",
    "@nrwl/eslint-plugin-nx": "9.4.5",
    "@typescript-eslint/parser": "2.19.2",
    "@typescript-eslint/eslint-plugin": "2.19.2",
    "eslint-config-prettier": "6.0.0",
    "eslint-plugin-import": "2.20.2",
    "eslint-plugin-jsx-a11y": "6.2.3",
    "eslint-plugin-react": "7.20.0",
    "eslint-plugin-react-hooks": "4.0.2",
    "node-sass": "4.14.1",
    "gatsby-plugin-sass": "2.3.3"
  }
}
```

I tried to `npm install gatsby-cli` but it does not solve the problem.

Any idea ?

**Comment by maxkoretskyi** [comment]
Hey @marcpicaud , I just tested it using `yarn` instead of `npm`, works for me, could you please try? Also, what is your environment?

**Comment by marcpicaud** [comment]
@maxkoretskyi Hey, thanks for your time. I just tried with yarn with the above package.json and it works fine. Super weird.

I re-tried with npm and the error is still there. My environment is : MacOS, Node v10.19.0 (through nvm) , npm v6.13.4.

I also tried with Node v12 and npm v6.14.4, same result.

https://github.com/nrwl/nx/issues/3247

**Comment by tremppu** [comment]
I'm having same issue with Windows 10 + npm.  Just installed newest version of everything.

**Comment by ruslanguns** [comment]
I am just getting

```bash
➜  televoip-workspace git:(master) ✗ nx serve ui-gatsby-starter       

> ng run ui-gatsby-starter:serve 
Error during serve
```

With no any other log ... just throws that ... any clue ?

**Comment by erkobridee** [comment]
my solution was the same of @tremppu, I have the [gatsby-cli as a devDependency on my project](https://github.com/erkobridee/nx-gatsby/blob/master/package.json#L72) and that makes it work 😄 
- [[GitHub] erkobridee/nx-gatsby](https://github.com/erkobridee/nx-gatsby)

**Comment by jaysoo** [comment]
There was an issue because `gatsby-cli` wasn't a direct dependency, so it's location is not guaranteed to be in `node_modules/gatsby-cli`. I've updated the builders to use `require.resolve` + added `gatsby-cli` as a dependency of `@nrwl/gatsby`.
