### ISSUE TITLE
If using custom directory serve does not work 

### ISSUE THREAD

**Issue by ruslanguns** [nrwl/gatsby#23]
I am just getting

```bash
➜  nx-workspace git:(master) ✗ nx serve gatsby-myblog    

> ng run ui-gatsby-starter:serve 
Error during serve
```

To reproduce it:

```bash
nx generate @nrwl/gatsby:app myblog --directory=gatsby // it creates the app at apps/gatsby/myblog

nx serve gatsby-myblog // that throws the error.
```
With no any other log ... just throws that ... any clue ?

BTW. if I don't use the custom directory and just create the app right into the apps folder it works properly, weid eh ?

**Comment by ruslanguns** [comment]
Just commenting it out. That is new for me, never seen it before when I have created using custom directories, it usually prepend the directory name in the launch script in the angular.json / workspace.json, but with gatsby it doesn't happen, not sure if that comes with the NX v10 however I will close this issue since this behavior is now expected.

**Comment by Bulletninja** [comment]
I did something like this:

> nx g @nrwl/gatsby:app www --directory="../manage-memberships/clients"

the relative path kind of worked, but had to cleanup some files. I did have the same error as yours, after `gatsby clean`ing, removing the lock and reinstaling i decided to directly run some gatsby cli commands, and cornered the error in the build process with this error:

```
Missing onError handler for invocation 'building-schema', error was 'Error: Cannot create as TypeComposer the following value: ImageFormat.'. 
Stacktrace was 'Error: Cannot create as TypeComposer the following value: ImageFormat.
```

**Comment by vincentwuhrlin** [comment]
Hello, the "apps" is hardcoded in builder [here].(https://github.com/nrwl/gatsby/blob/7b143000f97b82c7d2891d25d725b945c0d9c060/packages/gatsby-plugin/src/builders/server/builder.ts#L86
)
It is possible to correct this ?

I have discovered NX and I become a great fan, but due to this limitation, I am currently blocked for my project (custom directories).
