### ISSUE TITLE
nx cli v10 and latest gatsby plugin using tslint for e2e project

### ISSUE THREAD

**Issue by servrox** [nrwl/gatsby#26]
Following the [getting started](https://github.com/nrwl/gatsby#getting-started) guide creates an e2e project, using `"builder": "@angular-devkit/build-angular:tslint"` for linting.

Using `nx lint <app-name>` leads to an error:

> Cannot find module '@angular-devkit/build-angular/package.json'

---

When using `nx g @nrwl/gatsby:app <app-name>` an e2e project with following lint configuration should be created instread:
```
"lint": {
     "builder": "@nrwl/linter:lint",
     "options": {
          "linter": "eslint",
          "tsConfig": ["apps/<app-name>/tsconfig.e2e.json"],
          "exclude": ["**/node_modules/**", "!apps/<app-name>/**/*"]
     }
}
```

---

This can be achieved when using  `@nrwl/cypress@10.2.1` instead of `@nrwl/cypress@9.7.0`.

To manually achieve a e2e project creation without tslint, use  
`npm i --save-dev @nrwl/cypress@latest `
before running 
`nx g @nrwl/gatsby:app <app-name>`

---

Is there any reason why the gatsby-plugin is not using the newest @nrwl packages?
If not, I would suggest to update the deps in `/gatsby/packages/gatsby-plugin/package.json`

```
 @nrwl/react           ^9.4.5  →  ^10.2.1
 @nrwl/cypress         ^9.4.5  →  ^10.2.1
 @nrwl/jest            ^9.4.5  →  ^10.2.1
 @nrwl/workspace  ^9.4.0-rc.6  →  ^10.2.1
```

**Comment by servrox** [comment]
#27

**Comment by supaspoida** [comment]
I am seeing a lot of warnings and possible some errors that appear related to these package versions when trying to use this plugin with the latest nx workspace version. Would be great to get #27 merged in and released if possible, thanks!

**Comment by jaysoo** [comment]
Nx 10 is now supported. The lint setup has changed drastically, so you will need to migrate existing workspaces.
```sh
nx migrate @nrwl/workspace:latest
yarn # or npm install
nx migrate --run-migrations=migrations.json
```
