### ISSUE TITLE
How to run gatsby clean ?

### ISSUE THREAD

**Issue by gauravsaini** [nrwl/gatsby#35]
How can I cleanup the old stuff similar to gatsby clean ?

**Comment by tujoworker** [comment]
This is not supported yet, but relative easy to add. I did misunderstand in the beginning the different terms NX uses, so I added PR to add "develop" – but NX calls that for "serve". This misunderstanding made me creating [this PR](https://github.com/nrwl/gatsby/pull/25/commits/961c9319f5623a7b6ee187e75b87e4806cb9a60b). So adding the clean command would be basically very similar.

I just saw your question, and thought I can give some value to it.

**Comment by jaysoo** [comment]
One thing you could do is add `run-commands` targets to your `workspace.json` file. We should probably generate the apps with the clean targets.

Either run this:

```sh
# Replace my-app with your app name
npx nx g @nrwl/workspace:run-commands clean --project my-app --command "node ../../node_modules/.bin/gatsby clean" --cwd "apps/my-app"
```

Or add it manually to your `targets`:

```
{
"projects":
  {
    "my-app": {
      ...
      "targets": {
        ...
          "clean": {
            "builder": "@nrwl/workspace:run-commands",
            "outputs": [],
            "options": {
              "command": "node ../../node_modules/.bin/gatsby clean",
              "cwd": "apps/my-app"
            }
          }
      }
    }
}
```
