### ISSUE TITLE
Update to gatsby version 3.0.1

### ISSUE THREAD

**Issue by Himadu2000** [nrwl/gatsby#41]
Please update to gatsby v3.

**Comment by jugglingcats** [comment]
```
warn Plugin nx-gatsby-ext-plugin is not compatible with your gatsby version 3.0.3 - It requires gatsby@^2.6.0
```

**Comment by jugglingcats** [comment]
Alternatively make `gatsby-cli` a peer dependency? Am seeing the following in my dependencies:
```
$ npm ls graphql
glowbuzzer@0.0.0 D:\alfie\gb\frontend
+-- @nrwl/gatsby@11.4.0
| `-- gatsby-cli@2.19.2
|   `-- gatsby-recipes@0.9.2
|     `-- graphql@14.7.0
+-- gatsby@3.0.3
| +-- gatsby-cli@3.0.0
| | `-- gatsby-recipes@0.11.0
| |   `-- graphql@15.5.0  deduped
| `-- graphql@15.5.0
`-- graphql@14.7.0
```

**Comment by Himadu2000** [comment]
Moving this issue to main Nx monorepo because this repo is moved [https://github.com/nrwl/nx/issues/6040](link), A suggestion to archive or delete this repo was also issued in this repo. #43

**Comment by FrozenPandaz** [comment]
Closing this PR as this repo has been moved to https://github.com/nrwl/nx
