### ISSUE TITLE
Gatsby and Chakra

### ISSUE THREAD

**Issue by dustinlacewell** [nrwl/gatsby#42]
Sorry for the issue, I'm really not sure where to seek help with this issue.

The chakra plugin for gatsby is not transpiled and contains some JSX code.

As I understand it, Gatsby automatically performs transpilation of dependencies in the project. However, with NX all the dependencies are located in the  workspace, and so this fails.

I'm relatively new to monorepos, and NX, so I'd appreciate if anyone had some guidance.

There was a previous issue around this and I commented there: https://github.com/gatsbyjs/gatsby/issues/19042

**Comment by FrozenPandaz** [comment]
Closing this PR as this repo has been moved to https://github.com/nrwl/nx
